lexer grammar windxer;

COMPONENTKEYWORD: 'component ';
STATEKEYWORD: '@States ';
PROPKEYWORD: '@Properties ';
STYLEDECL: LCORCH STRING RCORCH;
ID: [a-zA-Z_][a-zA-Z0-9_]*;
STRING : '"' (~["\\])* '"';
DASHCOND: '--' ID;
CONDREPRKEYWORD: '?' ID;
LPAREN: '(';
RPAREN: ')';
LBRACE: '{';
RBRACE: '}';
DOT: '.';
SEMICOLON: ';';
COLON: ':';
QUOTE: '"';
COMMA: ',';
LCORCH: '[';
RCORCH: ']';
WS: [ \t\r\n]+ -> skip;